repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml

    - repo: local
      hooks:
          - id: ktlint
            name: ktlint
            entry: ./gradlew lintKotlin
            language: system
            types: [kotlin]

          - id: detekt
            name: detekt
            entry: ./gradlew detekt
            language: system
            types: [kotlin]
